* About
ii-mode is an Emacs mode for handling files created by ii. I wrote this because i was fed up with being logged out of my servers at each Emacs restart. Also, I find it much cleaner to use Emacs as an interface to external programs rather than running them inside the editor. You can also close channel buffers without parting from them.
* License
GPL v3 or later.
* Dependencies
- GNU Emacs :: not tested in any other flavor.
- ii :: The minimalist filesystem based irc client from [[http://tools.suckless.org/ii/][suckless]]. 
- inotify-tools :: ii-mode uses inotifywait from this package to keep track of file changes.
* How to use

For now this mode requires my own patched version of ii, to be found at http://github.com/krl/ii

Put ii-mode.el in your emacs path and write something like this in your init file:

: (require 'ii-mode)
:  (setf ii-irc-directory "/home/username/irc/")
:  (add-to-list 'auto-mode-alist `(,(concat ii-irc-directory ".*/out\\'") . ii-mode))

To customize behavior you can use ii-mode-hook, this is what I do:

: (add-hook 'ii-mode-hook (lambda () 
:                           (visual-line-mode)                          
:                           (local-set-key (kbd "RET") 'newline)
:                           (local-set-key (kbd "C-c C-s") 'ii-send-message)))

* Notification
By default, you only get notified on queries. To ii-mode, this is channels with directories not starting with "#" or "&". To get notified on mentioning of your user name or favourite dish just set the variable 'ii-notify-regexps in your config like this:

: (setf ii-notify-regexps '("\\bkrl\\b" "\\bkrrl\\b"))

If you have a channel you want to keep extra track of, put it in the list 'ii-notify-channels and you will be bugged when it's updated.

: (setf ii-notify-channels '("irc.efnet.net/#data_kraft"))

You will se a "*ii*" in the global modeline when a notification is activated. To see which and/or to visit them, bind the command 'ii-visit-notified-file to a key sequence of choice.

To visit any of the channels tracked by ii-mode use 'ii-visit-channel-file, and to visit any of the server channels use 'ii-visit-server-file.

* Left to do 
There's still stuff to be done to make it really sweet.

- previous entries ring
- fix the annoying buffer modified really kill etc things.

